server:
  port: 8084

spring:
  application:
    name: ms-bff

logging:
  level:
    cl.pymetrack.msbff: DEBUG
    org.springframework.web.reactive: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

services:
  ms-user: http://ms-user:8085/api/v1
  ms-productos: http://ms-productos:8081/api/v1
  ms-pedidos: http://ms-pedidos:8082/api/v1

app:
  bff:
    timeout: 5000
    retry-attempts: 2